### ISSUE TITLE
项目集成log-record通过k8s发布启动后报javassist.NotFoundException: cn.monitor4all.logRecord.function.CustomFunctionObjectDiff异常

### ISSUE THREAD

**Issue by jinyang-git-hub** [qqxx6661/log-record#46]
项目集成log-record通过k8s发布启动后报javassist.NotFoundException: cn.monitor4all.logRecord.function.CustomFunctionObjectDiff异常
但是本地通过idea启动是没问题的，以下是详细的错误日志，希望作者帮忙看一下

DEBUG 2022-12-20 10:50:39:929 main AgentPackagePath : The beacon class location is jar:file:/skywalking-agent/skywalking-agent.jar!/org/apache/skywalking/apm/agent/core/boot/AgentPackagePath.class. 
INFO 2022-12-20 10:50:39:932 main SnifferConfigInitializer : Config file found in /skywalking-agent/config/agent.config. 

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.5.1)

10:51:23.614 [main] INFO  [TID:N/A] com.toplion.download.DownloadCenterApplication - The following profiles are active: pre
10:53:03.515 [main] ERROR [TID:N/A] cn.monitor4all.logRecord.function.CustomFunctionRegistrar - cn.monitor4all.logRecord.function.CustomFunctionObjectDiff
javassist.NotFoundException: cn.monitor4all.logRecord.function.CustomFunctionObjectDiff
	at javassist.ClassPool.get(ClassPool.java:430)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.constructCtClass(CustomFunctionRegistrar.java:118)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.proxy2static(CustomFunctionRegistrar.java:104)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.lambda$setApplicationContext$4(CustomFunctionRegistrar.java:72)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.setApplicationContext(CustomFunctionRegistrar.java:43)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:128)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:102)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.toplion.download.DownloadCenterApplication.main(DownloadCenterApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
10:53:04.323 [main] ERROR [TID:N/A] org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'registrar' defined in class path resource [cn/monitor4all/logRecord/configuration/LogRecordConfiguration.class]: Initialization of bean failed; nested exception is java.lang.RuntimeException: javassist.NotFoundException: cn.monitor4all.logRecord.function.CustomFunctionObjectDiff
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:610)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.toplion.download.DownloadCenterApplication.main(DownloadCenterApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.RuntimeException: javassist.NotFoundException: cn.monitor4all.logRecord.function.CustomFunctionObjectDiff
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.lambda$setApplicationContext$4(CustomFunctionRegistrar.java:85)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.setApplicationContext(CustomFunctionRegistrar.java:43)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:128)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:102)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	... 23 common frames omitted
Caused by: javassist.NotFoundException: cn.monitor4all.logRecord.function.CustomFunctionObjectDiff
	at javassist.ClassPool.get(ClassPool.java:430)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.constructCtClass(CustomFunctionRegistrar.java:118)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.proxy2static(CustomFunctionRegistrar.java:104)
	at cn.monitor4all.logRecord.function.CustomFunctionRegistrar.lambda$setApplicationContext$4(CustomFunctionRegistrar.java:72)
	... 30 common frames omitted

**Comment by qqxx6661** [comment]
两位试下降低版本。1.3.1能否使用？目前初步怀疑是javaassist和应用有版本冲突

**Comment by qqxx6661** [comment]
解决方案请看下 #55
