### ISSUE TITLE
项目集成后通过docker部署到服务器javassist.NotFoundException：xxxxx.utils.function.CustomFunctionObjectDiff

### ISSUE THREAD

**Issue by TernenceZhou** [qqxx6661/log-record#55]
tils.function.CustomFunctionObjectDiff
        at javassist.ClassPool.get(ClassPool.java:430)
        at com.zeekr.speech.config.utils.function.CustomFunctionRegistrar.constructCtClass(CustomFunctionRegistrar.java:122)
        at com.zeekr.speech.config.utils.function.CustomFunctionRegistrar.proxy2static(CustomFunctionRegistrar.java:108)
        at com.zeekr.speech.config.utils.function.CustomFunctionRegistrar.lambda$setApplicationContext$4(CustomFunctionRegistrar.java:74)
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at com.zeekr.speech.config.utils.function.CustomFunctionRegistrar.setApplicationContext(CustomFunctionRegistrar.java:45)
        at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:123)
        at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:100)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:415)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1791)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
        at com.zeekr.speech.config.Application.main(Application.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Comment by qqxx6661** [comment]
你试一下使用1.3.x版本，例如1.3.1版本。我怀疑是javassist版本和你的应用有冲突。试一下

**Comment by TernenceZhou** [comment]
javassist的版本3.1是吗
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.15.0-GA</version>
</dependency>

**Comment by qqxx6661** [comment]
目前1.4.1版本强依赖了
```
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.29.2-GA</version>
</dependency>
```

**Comment by qqxx6661** [comment]
> javassist的版本3.1是吗 org.javassist javassist 3.15.0-GA

直接把log-record降低到1.3.1版本看下能否启动

**Comment by TernenceZhou** [comment]
会不会是其他依赖中引入了javassist ，导致的冲突。在其他依赖中做一下exclusion操作

**Comment by TernenceZhou** [comment]
我没有直接引入log-record的依赖，是自己做的定制化
1、项目中引入ibatis的javassist org.apache.ibatis.javassist.*
2、修改pom exclusion：
 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>transmittable-thread-local</artifactId>
            <version>2.14.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.javassist</groupId>
                    <artifactId>javassist</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
3、去掉了
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.29.2-GA</version>
</dependency>
启动还是异常

**Comment by qqxx6661** [comment]
> 会不会是其他依赖中引入了javassist ，导致的冲突。在其他依赖中做一下exclusion操作

应该以optional形式提供。 所以你试了1.3.1看看行不行？1.3.1不包含javaassist

**Comment by TernenceZhou** [comment]
> > 会不会是其他依赖中引入了javassist ，导致的冲突。在其他依赖中做一下exclusion操作
> 
> 应该以optional形式提供。 所以你试了1.3.1看看行不行？1.3.1不包含javaassist

您意思使用log-record-starter的1.3.1中的CustomFunctionRegistrar是吗
`<dependency>
            <groupId>cn.monitor4all</groupId>
            <artifactId>log-record-starter</artifactId>
            <version>1.3.1</version>
</dependency>`

**Comment by qqxx6661** [comment]
> > > 会不会是其他依赖中引入了javassist ，导致的冲突。在其他依赖中做一下exclusion操作
> > 
> > 
> > 应该以optional形式提供。 所以你试了1.3.1看看行不行？1.3.1不包含javaassist
> 
> 您意思使用log-record-starter的1.3.1中的CustomFunctionRegistrar是吗 `<dependency> <groupId>cn.monitor4all</groupId> <artifactId>log-record-starter</artifactId> <version>1.3.1</version> </dependency>`

是的，我意思是依赖版本先降到下面的1.3.1试下，看下应用能否恢复正常
```
<dependency>
  <groupId>cn.monitor4all</groupId>
  <artifactId>log-record-starter</artifactId>
  <version>1.3.1</version>
</dependency>
```

**Comment by TernenceZhou** [comment]
使用1.3.1版本的CustomFunctionRegistrar 启动正常，感谢作者的帮助
包含javaassist的异常原因还要继续探索

**Comment by qqxx6661** [comment]
> 使用1.3.1版本的CustomFunctionRegistrar 启动正常，感谢作者的帮助 包含javaassist的异常原因还要继续探索

好的，主要是在1.4.x版本引入了javaassist，并且强制限定了版本。导致和你们应用的版本冲突，导致里面的方法找不到。最近比较忙，等空下来，我解决下问题。

**Comment by qqxx6661** [comment]
您好，您自己应用里有引用javassist或者相关依赖吗？可以提供一个版本号给我。我排查下问题

**Comment by qqxx6661** [comment]
尝试修复了一版，可以试一下：
```
<dependency>
  <groupId>cn.monitor4all</groupId>
  <artifactId>log-record-starter</artifactId>
  <version>1.3.1</version>
</dependency>
```
